# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:

    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"

    default_config: my_config

    configs:
        my_config:
            toolbar: [
                [ "Maximize" ],
                [ 'Bold', 'Italic'],
                [ 'Format' ],
                [ 'Link', 'Unlink' ],
              #                      [ 'Table', 'Image' ],
                [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-'],
            ]
            format_tags: 'p;h1;h2;h3;h4;pre'

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

