framework:
    messenger:

        transports:
            liip_imagine: '%env(MESSENGER_TRANSPORT_DSN)%'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            'App\Message\SendEmail': async
            'Liip\ImagineBundle\Message\WarmupCache': liip_imagine
